"""Ed25519 against RFC 8032 §7.1. If these fail, `reg/ed25519.py` is wrong.

The vectors are copied from the RFC, not generated by the implementation: a
test that checks the code against its own output proves nothing. `sign` must
reproduce the RFC's signatures byte-for-byte (determinism is the point), and
`verify` must accept them and reject anything else.
"""

import pytest

from reg import ed25519

# (seed, public key, message, signature) — RFC 8032 §7.1, copied verbatim:
# TEST 1 (empty message), TEST 2, TEST 3, and TEST SHA(abc).
VECTORS = (
    (
        "9d61b19deffd5a60ba844af492ec2cc4"
        "4449c5697b326919703bac031cae7f60",
        "d75a980182b10ab7d54bfed3c964073a"
        "0ee172f3daa62325af021a68f707511a",
        "",
        "e5564300c360ac729086e2cc806e828a"
        "84877f1eb8e5d974d873e06522490155"
        "5fb8821590a33bacc61e39701cf9b46b"
        "d25bf5f0595bbe24655141438e7a100b",
    ),
    (
        "4ccd089b28ff96da9db6c346ec114e0f"
        "5b8a319f35aba624da8cf6ed4fb8a6fb",
        "3d4017c3e843895a92b70aa74d1b7ebc"
        "9c982ccf2ec4968cc0cd55f12af4660c",
        "72",
        "92a009a9f0d4cab8720e820b5f642540"
        "a2b27b5416503f8fb3762223ebdb69da"
        "085ac1e43e15996e458f3613d0f11d8c"
        "387b2eaeb4302aeeb00d291612bb0c00",
    ),
    (
        "c5aa8df43f9f837bedb7442f31dcb7b1"
        "66d38535076f094b85ce3a2e0b4458f7",
        "fc51cd8e6218a1a38da47ed00230f058"
        "0816ed13ba3303ac5deb911548908025",
        "af82",
        "6291d657deec24024827e69c3abe01a3"
        "0ce548a284743a445e3680d7db5ac3ac"
        "18ff9b538d16f290ae67f760984dc659"
        "4a7c15e9716ed28dc027beceea1ec40a",
    ),
    (
        "833fe62409237b9d62ec77587520911e"
        "9a759cec1d19755b7da901b96dca3d42",
        "ec172b93ad5e563bf4932c70e1245034"
        "c35467ef2efd4d64ebf819683467e2bf",
        "ddaf35a193617abacc417349ae204131"
        "12e6fa4e89a97ea20a9eeee64b55d39a"
        "2192992a274fc1a836ba3c23a3feebbd"
        "454d4423643ce80e2a9ac94fa54ca49f",
        "dc2a4459e7369633a52b1bf277839a00"
        "201009a3efbf3ecb69bea2186c26b589"
        "09351fc9ac90b3ecfdfbc7c66431e030"
        "3dca179c138ac17ad9bef1177331a704",
    ),
)


def test_vectors_are_well_formed():
    """A transcription guard: seeds are 32 bytes, public keys 32, signatures
    64. A dropped hex digit must fail here, not as a mysterious vector
    mismatch."""
    for seed_hex, public_hex, message_hex, signature_hex in VECTORS:
        assert len(seed_hex) == 64, seed_hex
        assert len(public_hex) == 64, public_hex
        assert len(signature_hex) == 128, signature_hex
        assert len(message_hex) % 2 == 0


@pytest.mark.parametrize(
    "seed_hex,public_hex,message_hex,signature_hex", VECTORS
)
def test_rfc8032_vectors(seed_hex, public_hex, message_hex, signature_hex):
    """The RFC's keys, signatures and messages, byte for byte."""
    seed = bytes.fromhex(seed_hex)
    public = bytes.fromhex(public_hex)
    message = bytes.fromhex(message_hex)
    signature = bytes.fromhex(signature_hex)
    assert ed25519.public_key(seed) == public
    # Deterministic: the RFC's signature, not just *a* valid one.
    assert ed25519.sign(seed, message) == signature
    assert ed25519.verify(public, message, signature) is True


@pytest.mark.parametrize(
    "seed_hex,public_hex,message_hex,signature_hex", VECTORS
)
def test_flipped_bits_do_not_verify(seed_hex, public_hex, message_hex, signature_hex):
    """NEGATIVE. One flipped bit anywhere in the signature is a rejection."""
    public = bytes.fromhex(public_hex)
    message = bytes.fromhex(message_hex)
    bad = bytearray.fromhex(signature_hex)
    bad[17] ^= 0x04
    assert ed25519.verify(public, message, bytes(bad)) is False


def test_malformed_inputs_are_false_not_exceptions():
    """NEGATIVE. A verifier checking attacker-controlled bytes must not throw."""
    seed = bytes.fromhex(VECTORS[0][0])
    public = ed25519.public_key(seed)
    good = ed25519.sign(seed, b"epoch checkpoint")
    assert ed25519.verify(public, b"epoch checkpoint", good) is True
    assert ed25519.verify(b"short", b"epoch checkpoint", good) is False
    assert ed25519.verify(public, b"epoch checkpoint", b"short") is False
    assert ed25519.verify(public, b"other message", good) is False
    assert ed25519.verify(b"\x00" * 32, b"epoch checkpoint", good) is False


def test_seed_length_is_refused():
    """A seed that is not 32 bytes is a caller error, loud."""
    with pytest.raises(ValueError, match="32 bytes"):
        ed25519.public_key(b"\x01" * 31)
    with pytest.raises(ValueError, match="32 bytes"):
        ed25519.sign(b"\x01" * 33, b"m")


def test_sign_is_deterministic():
    """Same seed and message, same signature, twice. The epoch checkpoints
    depend on this: a rebuild must produce byte-identical signatures."""
    seed = bytes.fromhex(VECTORS[1][0])
    assert ed25519.sign(seed, b"checkpoint") == ed25519.sign(seed, b"checkpoint")


def test_seed_bytes_agrees_with_the_check():
    """The constant and the refusal cannot drift apart unnoticed."""
    assert ed25519.seed_bytes() == ed25519.SEED_BYTES == 32
