#!/usr/bin/env python3
"""Record a `reg` fixture stream as a real rosbag2 bag and report its bytes.

**This is the script that produced `reg.bench.ROSBAG2_MEASUREMENTS`.** It runs
inside a ROS 2 container, not on this repository's host, and it is checked in so
that the numbers `docs/sensor-baseline.md` publishes can be regenerated by
somebody who is not us. A measurement nobody else can reproduce is an assertion
(`docs/prior-art.md` §27, Reproducible Builds).

Nothing here is imported by `reg`. It reads a CSV that `python -m reg.sim`
already wrote and writes a bag beside it, so no dependency reaches the package —
`docs/plan.md`'s no-new-dependencies rule is intact, and `scripts/` is where
`check_bench_determinism.py` already establishes that pattern.

WHAT THIS SETTLES
-----------------
`docs/sensor-baseline.md` prices the incumbent from the MCAP specification. That
projection needed checking against a real encoder, and specifically against
**rosbag2's own C++ writer**, because the specification says nothing about which
preset rosbag2 selects or what compression level that preset uses. Running it
found four things, all recorded in `reg.bench`:

1. the uncompressed projection is right to +0.002% on `long_run_3000`;
2. rosbag2's default really is uncompressed (an unset profile and the explicit
   `none` profile differ by 4 bytes on a 1.6 MB bag);
3. the 16 B/message index derived from the specification measures at 16.06 B,
   isolated as `none` minus `fastwrite`;
4. the preset names this repository had published — `mcap_default` and
   `mcap_compressed_nocrc` — are mcap.dev's *benchmark* vocabulary and are
   **rejected** by `--storage-preset-profile`.

HOW TO RUN IT
-------------
From the repository root, with Docker running::

    python -m reg.sim --scenario long_run_3000 --seed 0 --out /tmp/rb/lr.csv
    docker run --rm -v /tmp/rb:/w -w /w ros:jazzy bash -lc '
        source /opt/ros/jazzy/setup.bash
        python3 /w/record_rosbag2.py --csv /w/lr.csv --preset "" --out /w/bag'

`--preset ""` means *pass no profile at all*, which is what a practitioner gets
by default. The named profiles are `none`, `fastwrite`, `zstd_fast` and
`zstd_small`; see `reg.bench.ROSBAG2_STORAGE_PRESET_PROFILES`.

THE BAG'S SIZE DEPENDS ON THE DIRECTORY YOU NAME. READ THIS BEFORE COMPARING.
-----------------------------------------------------------------------------
**Four bytes per character of the output directory name**, measured::

    --out b_lr_none        (9 chars)   1,637,967 B   <- the published figure
    --out v_none           (6 chars)   1,637,955 B
    --out xxxxxxxxxx_none  (15 chars)  1,637,991 B

rosbag2 embeds a copy of `metadata.yaml` in the `.mcap`, and the bag name occurs
**four times** inside it — twice under `relative_file_paths:` and twice under
`files:`, in two copies of the block. So the name is in the byte count, four
times over.

`reg.bench.ROSBAG2_MEASUREMENTS` records the figures produced with the directory
names ``b_dv_<profile>`` and ``b_lr_<profile>``. **Reproducing those bytes
exactly requires those names.** A run with a different name is right about the
encoding and wrong in the last two digits, which on a comparison this project
publishes to five significant figures is the difference between a validation and
a near-miss.

It also means the figure is not purely a property of the content, and a
comparison against the gzipped CSV carries a few dozen bytes of bag-naming in it.
At 1.6 MB that is under 0.002% and does not move any published ratio; it is
recorded because a number whose reproduction depends on something unstated is the
defect `docs/self-describing.md` is about, and finding it here rather than in
somebody else's failed reproduction is the whole reason this file is checked in.

THREE MORE THINGS THAT COST A RUN EACH, WRITTEN DOWN SO THEY COST NOBODY ELSE ONE
---------------------------------------------------------------------------------
Every one of these was a failed run on 2026-09-06, and none of them is in the
`rosbag2_py` documentation in a form that would have prevented it.

* **`TopicMetadata` takes a positional `id` in Jazzy.** The keyword-only form
  that reads naturally — ``TopicMetadata(name=..., type=...,
  serialization_format=...)`` — raises ``TypeError: incompatible constructor
  arguments``. The signature is ``(id, name, type, serialization_format,
  offered_qos_profiles=[], type_description_hash='')``.
* **An unset `storage_preset_profile` is not the same case as `none`.**
  Constructing ``StorageOptions(..., storage_preset_profile="")`` is not the same
  as omitting the argument, and the whole question *does rosbag2 compress by
  default* turns on being able to record both. They come out 4 bytes apart, which
  is the answer, but you cannot get it if the script conflates them.
* **The preset name is validated late and fatally.** An unknown profile fails at
  ``writer.open()`` with ``No storage could be initialized. Abort``, after the
  topics are set up. The valid list is only in the error text.

WHAT IS DELIBERATELY NOT HERE
-----------------------------
No comparison, no ratio, no verdict. This prints bytes. Turning bytes into a
figure is `reg.bench`'s job and it is tested there; a script that also computed
the answer would be a second implementation of the comparison, free to disagree
with the one under test.
"""

from __future__ import annotations

import argparse
import csv
import json
import pathlib
import sys

import rclpy.serialization
import rosbag2_py
from geometry_msgs.msg import TransformStamped
from sensor_msgs.msg import JointState
from tf2_msgs.msg import TFMessage

#: Profiles `--storage-preset-profile` accepts in Jazzy, from the error text a
#: rejected name produces. `mcap_default` and `mcap_compressed_nocrc` are **not**
#: among them; they are mcap.dev's benchmark vocabulary and this repository
#: published them by mistake until issue #232.
VALID_PROFILES = ("none", "fastwrite", "zstd_fast", "zstd_small")


def rows(path: str) -> list[dict[str, str]]:
    """The stream's data rows, without its `#` provenance banner."""
    text = [l for l in pathlib.Path(path).read_text().splitlines()
            if not l.startswith("#")]
    return list(csv.DictReader(text))


def joint_state(r: dict[str, str], joints: int) -> JointState:
    """`sensor_msgs/JointState` for one frame.

    `effort` is left empty and the joint names are the shortest plausible
    (`j0`, `j1`, ...). Both choices make the bag *smaller*, which makes the
    incumbent look cheaper and this project's ratio against it larger — the
    direction an honest comparison errs in. `reg.bench` states the same
    assumptions.
    """
    m = JointState()
    t = float(r["t"])
    m.header.stamp.sec = int(t)
    m.header.stamp.nanosec = int(round((t - int(t)) * 1e9))
    m.header.frame_id = ""
    m.name = [f"j{i}" for i in range(joints)]
    m.position = [float(r[f"q_{i}"]) for i in range(joints)]
    m.velocity = [float(r[f"qd_{i}"]) for i in range(joints)]
    m.effort = []
    return m


def tf_message(r: dict[str, str], entities: list[tuple[str, str, str]]) -> TFMessage:
    """One `tf2_msgs/TFMessage` carrying every entity's pose for one frame.

    A `/tf` tree rather than a `PoseStamped` per entity, because issue #220
    priced both and this one is smaller — the arrangement most favourable to the
    incumbent. Identity rotation: the stream carries positions only, and
    inventing an orientation would put bytes in the bag that no measurement
    supports.
    """
    m = TFMessage()
    t = float(r["t"])
    for name, xk, yk in entities:
        tr = TransformStamped()
        tr.header.stamp.sec = int(t)
        tr.header.stamp.nanosec = int(round((t - int(t)) * 1e9))
        tr.header.frame_id = "map"
        tr.child_frame_id = name
        tr.transform.translation.x = float(r[xk])
        tr.transform.translation.y = float(r[yk])
        tr.transform.rotation.w = 1.0
        m.transforms.append(tr)
    return m


def entities_in(header: list[str]) -> list[tuple[str, str, str]]:
    """`(name, x column, y column)` per entity the stream carries.

    Matched by shape rather than by a hard-coded list, so a fixture that gains an
    obstacle is priced with it. `human_vx` does not match: the test is a `_x`
    suffix with a `_y` sibling, and `human_vx`'s last two characters are `vx`.
    Base columns are excluded — a mobile fixture's base is the robot, not an
    entity, and it belongs to `/joint_states`' side of the Layer A / Layer B line
    (`docs/sufficiency.md` §5.6).
    """
    out = []
    for k in header:
        if k.endswith("_x") and not k.startswith("base"):
            stem = k[:-2]
            if f"{stem}_y" in header:
                out.append((stem, k, f"{stem}_y"))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Record a reg fixture stream as a rosbag2 bag; print bytes.")
    ap.add_argument("--csv", required=True, help="a stream python -m reg.sim wrote")
    ap.add_argument("--out", required=True, help="bag directory to create")
    ap.add_argument(
        "--preset", required=True,
        help=f"storage preset profile, one of {VALID_PROFILES}, or \"\" to pass "
             "none at all (which is what a practitioner gets by default and is a "
             "different case from the 'none' profile)")
    a = ap.parse_args()

    if a.preset != "" and a.preset not in VALID_PROFILES:
        # Checked here as well as by rosbag2, because rosbag2 checks it at
        # `open()` — after the topics are created and with a message that says
        # only "No storage could be initialized".
        print(f"unknown preset {a.preset!r}; rosbag2 accepts {VALID_PROFILES} "
              'or "" for no profile at all', file=sys.stderr)
        return 2

    data = rows(a.csv)
    if not data:
        print("empty stream — refusing rather than recording a bag of nothing",
              file=sys.stderr)
        return 2

    head = list(data[0])
    joints = len([k for k in head if k.startswith("q_")])
    ents = entities_in(head)
    if not joints or not ents:
        # Refusing rather than recording half the content: a bag with no `/tf`
        # would be priced against a gzipped CSV that has the entity columns in
        # it, and the comparison would be between different information.
        print(f"joints={joints} entities={len(ents)} — refusing rather than "
              "recording half the stream's content", file=sys.stderr)
        return 2

    # An unset profile and the explicit 'none' profile are different cases and
    # the difference is the finding: 1,637,963 B against 1,637,967 B on
    # long_run_3000, which is what settles that rosbag2 does not compress by
    # default. Constructing StorageOptions with an empty string would conflate
    # them, so the argument is omitted entirely.
    opts = (rosbag2_py.StorageOptions(uri=a.out, storage_id="mcap")
            if a.preset == "" else
            rosbag2_py.StorageOptions(uri=a.out, storage_id="mcap",
                                      storage_preset_profile=a.preset))

    w = rosbag2_py.SequentialWriter()
    w.open(opts, rosbag2_py.ConverterOptions("", ""))
    for i, (topic, typ) in enumerate(
            (("/joint_states", "sensor_msgs/msg/JointState"),
             ("/tf", "tf2_msgs/msg/TFMessage")), start=1):
        # `id` is positional-required in Jazzy. The keyword-only form raises
        # `TypeError: incompatible constructor arguments`.
        w.create_topic(rosbag2_py.TopicMetadata(
            id=i, name=topic, type=typ, serialization_format="cdr"))

    for r in data:
        ns = int(round(float(r["t"]) * 1e9))
        w.write("/joint_states",
                rclpy.serialization.serialize_message(joint_state(r, joints)), ns)
        w.write("/tf",
                rclpy.serialization.serialize_message(tf_message(r, ents)), ns)
    del w  # closes the bag; the writer has no explicit close() in Jazzy

    files = sorted(pathlib.Path(a.out).glob("*.mcap"))
    if not files:
        print(f"no .mcap written under {a.out} — refusing to report 0 bytes",
              file=sys.stderr)
        return 2
    print(json.dumps({
        "preset": a.preset or "<unset: rosbag2 default>",
        "frames": len(data),
        "messages": len(data) * 2,
        "joints": joints,
        "entities": [e[0] for e in ents],
        "mcap_files": [f.name for f in files],
        "mcap_bytes": sum(f.stat().st_size for f in files),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
